import React from 'react';
import './AssessmentDetail.css';

const AssessmentDetail = ({ assessment, onClose, userEmail }) => {
  if (!assessment) return null;

  return (
    <div className="animate-fade-in detail-page">
      <div className="detail-header-actions no-print">
        <button className="btn btn-secondary" onClick={onClose}>
          &larr; Back to Assessment List
        </button>
        <button className="btn btn-primary ml-auto" onClick={() => window.print()}>
          Export PDF
        </button>
      </div>

      <div className="glass-container detail-container print-container">
        <div className="print-only print-header">
          <h2>AC Mobility Field Assessment Report</h2>
          <p>Generated on: {new Date().toLocaleString()}</p>
          <p>Generated by: {userEmail || 'Unknown User'}</p>
          <hr />
        </div>
        
        <div className="detail-header">
          <h2>Assessment: {assessment.assessment_id}</h2>
          <span className="text-muted">Recorded on {new Date(assessment.created_at).toLocaleString()}</span>
        </div>

        <div className="detail-body">
          <div className="details-grid-full">
            {Object.entries(assessment).map(([key, value]) => {
              if (key === 'id' || key === 'created_at' || value === null || value === '') return null;
              
              // Format key names
              const formattedKey = key
                .split('_')
                .map(word => word.charAt(0).toUpperCase() + word.slice(1))
                .join(' ');

              return (
                <div className="detail-card" key={key}>
                  <span className="detail-label">{formattedKey}</span>
                  <span className="detail-value">{
                    typeof value === 'boolean' ? (value ? 'Yes' : 'No') : 
                    value instanceof Date ? new Date(value).toLocaleString() : 
                    value.toString()
                  }</span>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
};

export default AssessmentDetail;
